"""Initial migration

Revision ID: 7d90b8799a97
Revises: 
Create Date: 2025-10-20 22:44:13.002608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d90b8799a97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_create_assignments', sa.Boolean(), nullable=False),
    sa.Column('can_create_users', sa.Boolean(), nullable=False),
    sa.Column('sbc_code', sa.String(length=50), nullable=True),
    sa.Column('sbc_company_name', sa.String(length=255), nullable=True),
    sa.Column('sbc_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('sbc_contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['internal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'internal_users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'internal_users', ['email'], unique=False)
    op.create_index('idx_user_role', 'internal_users', ['role'], unique=False)
    op.create_index('idx_user_role_active', 'internal_users', ['role', 'is_active'], unique=False)
    op.create_index('idx_user_sbc_code', 'internal_users', ['sbc_code'], unique=False)
    op.create_index(op.f('ix_internal_users_email'), 'internal_users', ['email'], unique=True)
    op.create_index(op.f('ix_internal_users_role'), 'internal_users', ['role'], unique=False)
    op.create_index(op.f('ix_internal_users_sbc_code'), 'internal_users', ['sbc_code'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internal_po_id', sa.String(length=50), nullable=False),
    sa.Column('created_by_pm_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_sbc_id', sa.UUID(), nullable=False),
    sa.Column('pd_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('admin_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('rejected_by_id', sa.UUID(), nullable=True),
    sa.Column('external_po_number', sa.String(length=100), nullable=False),
    sa.Column('external_po_line_numbers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_PD_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('assignment_notes', sa.Text(), nullable=True),
    sa.Column('pd_remarks', sa.Text(), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pd_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_approved_by_id'], ['internal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_sbc_id'], ['internal_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_pm_id'], ['internal_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pd_approved_by_id'], ['internal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['internal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_created', 'assignments', ['created_at'], unique=False)
    op.create_index('idx_assignment_external_po', 'assignments', ['external_po_number'], unique=False)
    op.create_index('idx_assignment_pm', 'assignments', ['created_by_pm_id', 'status'], unique=False)
    op.create_index('idx_assignment_sbc', 'assignments', ['assigned_to_sbc_id', 'status'], unique=False)
    op.create_index('idx_assignment_status', 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_assigned_to_sbc_id'), 'assignments', ['assigned_to_sbc_id'], unique=False)
    op.create_index(op.f('ix_assignments_created_by_pm_id'), 'assignments', ['created_by_pm_id'], unique=False)
    op.create_index(op.f('ix_assignments_external_po_number'), 'assignments', ['external_po_number'], unique=False)
    op.create_index(op.f('ix_assignments_internal_po_id'), 'assignments', ['internal_po_id'], unique=True)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_attempted', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['internal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_email', 'login_history', ['email_attempted', 'attempted_at'], unique=False)
    op.create_index('idx_login_ip', 'login_history', ['ip_address', 'attempted_at'], unique=False)
    op.create_index('idx_login_success', 'login_history', ['success', 'attempted_at'], unique=False)
    op.create_index('idx_login_user', 'login_history', ['user_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_history_attempted_at'), 'login_history', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_history_email_attempted'), 'login_history', ['email_attempted'], unique=False)
    op.create_index(op.f('ix_login_history_ip_address'), 'login_history', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_history_success'), 'login_history', ['success'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('permission_change_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_name', sa.String(length=255), nullable=True),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['internal_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['internal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_permission_changed_by', 'permission_change_logs', ['changed_by_id', 'changed_at'], unique=False)
    op.create_index('idx_permission_name', 'permission_change_logs', ['permission_name', 'changed_at'], unique=False)
    op.create_index('idx_permission_user', 'permission_change_logs', ['user_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_permission_change_logs_changed_at'), 'permission_change_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_permission_change_logs_changed_by_id'), 'permission_change_logs', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_permission_change_logs_permission_name'), 'permission_change_logs', ['permission_name'], unique=False)
    op.create_index(op.f('ix_permission_change_logs_user_id'), 'permission_change_logs', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['internal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('idx_session_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_token', 'user_sessions', ['token'], unique=False)
    op.create_index('idx_session_user', 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index('idx_session_user', table_name='user_sessions')
    op.drop_index('idx_session_token', table_name='user_sessions')
    op.drop_index('idx_session_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_permission_change_logs_user_id'), table_name='permission_change_logs')
    op.drop_index(op.f('ix_permission_change_logs_permission_name'), table_name='permission_change_logs')
    op.drop_index(op.f('ix_permission_change_logs_changed_by_id'), table_name='permission_change_logs')
    op.drop_index(op.f('ix_permission_change_logs_changed_at'), table_name='permission_change_logs')
    op.drop_index('idx_permission_user', table_name='permission_change_logs')
    op.drop_index('idx_permission_name', table_name='permission_change_logs')
    op.drop_index('idx_permission_changed_by', table_name='permission_change_logs')
    op.drop_table('permission_change_logs')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_success'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_ip_address'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_email_attempted'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_attempted_at'), table_name='login_history')
    op.drop_index('idx_login_user', table_name='login_history')
    op.drop_index('idx_login_success', table_name='login_history')
    op.drop_index('idx_login_ip', table_name='login_history')
    op.drop_index('idx_login_email', table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_internal_po_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_external_po_number'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_created_by_pm_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_to_sbc_id'), table_name='assignments')
    op.drop_index('idx_assignment_status', table_name='assignments')
    op.drop_index('idx_assignment_sbc', table_name='assignments')
    op.drop_index('idx_assignment_pm', table_name='assignments')
    op.drop_index('idx_assignment_external_po', table_name='assignments')
    op.drop_index('idx_assignment_created', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_internal_users_sbc_code'), table_name='internal_users')
    op.drop_index(op.f('ix_internal_users_role'), table_name='internal_users')
    op.drop_index(op.f('ix_internal_users_email'), table_name='internal_users')
    op.drop_index('idx_user_sbc_code', table_name='internal_users')
    op.drop_index('idx_user_role_active', table_name='internal_users')
    op.drop_index('idx_user_role', table_name='internal_users')
    op.drop_index('idx_user_email', table_name='internal_users')
    op.drop_index('idx_user_active', table_name='internal_users')
    op.drop_table('internal_users')
    # ### end Alembic commands ###
